# OVH API credentials used by Certbot
dns_ovh_endpoint = ovh-eu
dns_ovh_application_key = 2bd4220c8d6dd06b
dns_ovh_application_secret = c630f3fe304ee382e29c651fdafe33e3
dns_ovh_consumer_key = 8243d71042345f68d6a92c9de827d152
rspserver = https://acme-v02.api.letsencrypt.org/directory
