services:
  backend-nodejs-express:
    build:
      context: ./backend/
    container_name: backend-ocg
    ports:
      - "3000:3000"
  frontend-react:
    build:
      context: ./frontend/
    container_name: frontend-ocg
    environment:
      - REACT_APP_API_URL=api.ocg.martinld.fr
    volumes:
      - ./nginx/build/:/app/dist:rw
    depends_on:
      - backend-nodejs-express
  webserver-nginx:
    build:
      context: ./nginx/
    container_name: webserver-ocg
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
    depends_on:
      - frontend-react
    