services:
  frontend:
    build:
      context: /home/martinld/Documents/OpenCardsAI/frontend/
    container_name: nginx-react-ocg
    ports:
      - "8080:80"
    volumes:
      - /home/martinld/Documents/OpenCardsAI/frontend/.nginx:/etc/nginx/conf.d/
    environment:
      - API_URL=api.ocg.martinld.fr
  backend:
    build:
      context: /home/martinld/Documents/OpenCardsAI/backend/
    container_name: backend-ocg
    ports:
      - "3000:3000"
