services:
  frontend:
    build:
      context: ./frontend/
    container_name: frontend-ocg
    ports:
      - "8080:80"
    volumes:
      - ./frontend/.nginx:/etc/nginx/conf.d/:ro
    environment:
      - API_URL=api.ocg.martinld.fr
    depends_on:
      - backend
  backend:
    build:
      context: ./backend/
    container_name: backend-ocg
    ports:
      - "3000:3000"
