services:
  backend:
    build:
      context: ./backend/
    container_name: backend-ocg
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend/
    container_name: frontend-ocg
    ports:
      - "8080:80"
      - "4430:443"
    volumes:
      - ./frontend/.nginx/conf/:/etc/nginx/conf.d/:ro
      - ./frontend/.nginx/cerbot/:/etc/letsencrypt/:ro
    depends_on:
      - backend
