# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/martinld.fr
cert = /etc/letsencrypt/live/martinld.fr/cert.pem
privkey = /etc/letsencrypt/live/martinld.fr/privkey.pem
chain = /etc/letsencrypt/live/martinld.fr/chain.pem
fullchain = /etc/letsencrypt/live/martinld.fr/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 720947782df4e6bc9e122dcd5f5989cc
authenticator = dns-ovh
dns_ovh_credentials = /etc/letsencrypt/ovh_api_credentials.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
